#!/bin/sh

egencache --repo=JamesB192 --write-timestamp --tolerant \
 --update-manifests \
 --update-changelogs \
 --update-pkg-desc-index \
 --update-use-local-desc \
 --update

repoman -d \
 -x \
 --experimental-inherit y \
 --unmatched-removal \
 full
